DELETE http://localhost:3001/api/notes/4  HTTP/1.1
 



###

GET http://localhost:3001/api/notes HTTP/1.1

###
POST http://localhost:3001/api/notes HTTP/1.1
content-type: application/json


{   
  "name": "walter enzo",
    "number": 12342222222
}
 
### 
PUT http://localhost:3001/api/notes/643671f5124b841c0b0b72f8 HTTP/1.1
Content-Type: application/json

{
  "name": "wasd2a nota",
  "number": 123456789
}